apiVersion: 1

datasources:
  - name: PostgresDB
    type: postgres
    access: proxy
    url: gnome-db:5432
    user: gnome
    jsonData:
      database: gnome
      sslmode: disable     
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: gnome
    isDefault: false
    editable: true